package jdbctools;

public enum TableType {
	TABLE("table"),
	PARTITION_TABLE("PARTITIONED TABLE"),
	VIEW("VIEW"),
	INDEX("INDEX"),
	PARTITIONED_INDEX("PARTITIONED INDEX"),
	SEQUENCE("SEQUENCE"),
	TYPE("TYPE"),
	SYSTEM_TABLE("SYSTEM TABLE"),
	SYSTEM_TOAST_TABLE("SYSTEM TOAST TABLE"),
	SYSTEM_TOAST_INDEX("SYSTEM TOAST INDEX"),
	SYSTEM_VIEW("SYSTEM VIEW"),
	SYSTEM_INDEX("SYSTEM INDEX"),
	TEMPORARY_TABLE("TEMPORARY TABLE"),
	TEMPORARY_INDEX("TEMPORARY INDEX"),
	TEMPORARY_VIEW("TEMPORARY VIEW"),
	TEMPORARY_SEQUENCE("TEMPORARY SEQUENCE"),
	FOREIGN_FOREIGN_TABLE("PARTITIONED TABLE"),
	MATERIALIZED_VIEW("MATERIALIZED VIEW");
	private String value;
	
	private TableType(String type) {
		this.value = type;
	}
}
